In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [3]:
train = pd.read_csv("train.csv")
test = pd.read_csv('test.csv')
upload = pd.read_csv('upload.csv')
train = train.dropna(axis = 1, how = 'all')
test = test.dropna(axis = 1, how = 'all')
# test.head()

In [5]:
temp = ['RowNumber', 'CustomerId', 'Surname', 'Exited']
train_X = train.drop(temp, axis = 1) 
train_y = train['Exited']
test_X = test.drop(temp[0:3], axis = 1)

In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
labelencoder = LabelEncoder()
train_X['Geography'] = labelencoder.fit_transform(train_X['Geography'])
train_X['Gender'] = labelencoder.fit_transform(train_X['Gender'])
train_X['Age'] = preprocessing.scale(train_X['Age'])
train_X['Tenure'] = preprocessing.scale(train_X['Tenure'])
train_X['Balance'] = preprocessing.scale(train_X['Balance'])
train_X['EstimatedSalary'] = preprocessing.scale(train_X['EstimatedSalary'])


In [5]:
test_X['Geography'] = labelencoder.fit_transform(test_X['Geography'])
test_X['Gender'] = labelencoder.fit_transform(test_X['Gender'])
test_X['Age'] = preprocessing.scale(test_X['Age'])
test_X['Tenure'] = preprocessing.scale(test_X['Tenure'])
test_X['Balance'] = preprocessing.scale(test_X['Balance'])
test_X['EstimatedSalary'] = preprocessing.scale(test_X['EstimatedSalary'])

In [6]:
classifier = KNeighborsClassifier()
classifier.fit(train_X, train_y)
pred_y = classifier.predict(test_X)
pred_y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [9]:
upload['Exited'] = pred_y
upload.to_csv('1.csv')

In [7]:
classifer=LogisticRegression()
classifier.fit(train_X,train_y)
pred_yy=classifier.predict(test_X)
pred_yy

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
upload['Exited'] = pred_yy
upload.to_csv('2.csv')

In [8]:
from xgboost import XGBClassifier
xgboostModel = XGBClassifier(n_estimators=100, learning_rate= 0.3)
xgboostModel.fit(train_X,train_y)
# 使用訓練資料預測分類
predicted = xgboostModel.predict(test_X)
predicted

C:\Users\IDEA3C\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[15:01:27] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
upload['Exited'] = predicted
upload.to_csv('3.csv')